// <auto-generated />
using Albelli.OrderProcessor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Albelli.OrderProcessor.Api.Data.Migrations
{
    [DbContext(typeof(OrderProcessorDbContext))]
    [Migration("20220205002022_InitDatatbase")]
    partial class InitDatatbase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Albelli.OrderProcessor.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RequiredBinWidth")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RequiredBinWidth = 0m
                        },
                        new
                        {
                            Id = 2,
                            RequiredBinWidth = 0m
                        });
                });

            modelBuilder.Entity("Albelli.OrderProcessor.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 1,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Albelli.OrderProcessor.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StackItemsCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "photoBook",
                            StackItemsCount = 1,
                            Width = 19m
                        },
                        new
                        {
                            Id = 2,
                            Name = "calendar",
                            StackItemsCount = 1,
                            Width = 10m
                        },
                        new
                        {
                            Id = 3,
                            Name = "canvas",
                            StackItemsCount = 1,
                            Width = 16m
                        },
                        new
                        {
                            Id = 4,
                            Name = "cards",
                            StackItemsCount = 1,
                            Width = 4.7m
                        },
                        new
                        {
                            Id = 5,
                            Name = "mug",
                            StackItemsCount = 4,
                            Width = 94m
                        });
                });

            modelBuilder.Entity("Albelli.OrderProcessor.Api.Models.OrderItem", b =>
                {
                    b.HasOne("Albelli.OrderProcessor.Api.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Albelli.OrderProcessor.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Albelli.OrderProcessor.Api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
